services:
  bot:
    build:
      context: .
      target: dev
    env_file:
      - tbot/.env

  mongodb:
    image: mongo:7.0.14-jammy
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
